<?xml version="1.0" encoding="utf-8"?><Database Name="RealTimeTasks" Class="RealTimeTasksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=RealTimeTasks;Integrated Security=True" SettingsObjectName="RealTimeTasks.Data.Properties.Settings" SettingsPropertyName="RealTimeTasksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TaskItems" Member="TaskItems">
    <Type Name="TaskItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HandledBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsCompleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_TaskItem" Member="User" ThisKey="HandledBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="User_TaskItem" Member="TaskItems" ThisKey="Id" OtherKey="HandledBy" Type="TaskItem" />
    </Type>
  </Table>
</Database>